### ISSUE TITLE
umbrel-electrs uses the same port as umbrel-lightning, causing conflict

### ISSUE THREAD

**Issue by katokishin** [getumbrel/umbrel-electrs#2]
By default, umbrel-electrs specifies port 3006 in its `docker-compose.yml`
[Link to code](https://github.com/getumbrel/umbrel-electrs/blob/eb761bd6b45a5fcd08230669fc1c6e0f16a47b36/docker-compose.yml#L16)

However, umbrel-lightning also uses the same port for its GUI:
[Link to code](https://github.com/getumbrel/umbrel-lightning/blob/9e420ffe3c81694c63375548430a52600bb1088e/docker-compose.yml#L35)

As a result, running both apps causes a conflict that prevents access to both GUIs.

Proposed solution:
Change the port number used by umbrel-electrs or umbrel-lightning.

**Comment by TylonHH** [comment]
So I wonder why this issue so old and stil persist in the latest umbrel 1.3

anyway, I edited `/home/umbrel/umbrel/app-data/electrs/docker-compose.yml`

```
version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ELECTRS_IP
      APP_PORT: 3007
    container_name: electrs_app_proxy_1
```

Now electrs won't start.
whats the correct way for this workarround untill it's fixed?
